### PR TITLE
#167481871  Fix the application crash when navigating the application

### PR DESCRIPTION
**Pull request by ssewilliam**
#### What does this PR do?
Fix application crash when required data is not returned from the backend

#### Description of Task to be completed?
-  Fix application crash when required data is not returned from the backend

#### How should this be manually tested?
1. On the browser, go to https://staging-esa.andela.com
2. The application opens up a blank page after failing to access the updated data from the backend.

#### Any background context you want to provide?
- Validate data variables before accessing the value held by the variables

#### What are the relevant pivotal tracker stories?
[#167481871](https://www.pivotaltracker.com/story/show/167481871)

### CODE REVIEW

**Review by bozicschucky — APPROVED** [review]
Looks good to me.
Good work @ssewilliam .

**Review by emekafredy — COMMENTED** [review]
Why does the `test_ui_flow` test fail on circle-ci @ssewilliam? It seems to happen in all front-end PRs.

**Comment by ssewilliam** [comment]
@emekafredy we had decided to change the build workflow so that the **end to end tests** do not stop the build from being deployed to staging. Eventually, if staging was stable for both the backend and frontend. The next step would be to fix the failing **end to end tests**.

**Comment by emekafredy** [comment]
> @emekafredy we had decided to change the build workflow so that the **end to end tests** do not stop the build from being deployed to staging. Eventually, if staging was stable for both the backend and frontend. The next step would be to fix the end to end tests.

Cool @ssewilliam ... In my opinion, I actually think we should just have the e2e run locally.

**Review by emekafredy — APPROVED** [review]
LGTM

**Comment by ssewilliam** [comment]
Yes @emekafredy, I second you on that but unfortunately, some might not adhere to this convention when reviewing PRs that's why I believe it was enforced in the CI/CD pipeline with a uniform standard.

More on this is that since staging is up and running minimal fails should be expected such as the one on this [last build](https://circleci.com/gh/andela/bp-esa-frontend/1205)

**Pull request merged**
